#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Katherine Dykes, Ryan King and Yi Guo',
 'author_email': 'systems.engineering@nrel.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'Sizing model for wind turbine hub and nacelle components.',
 'download_url': '',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache v. 2.0',
 #'maintainer': '',
 #'maintainer_email': '',
 'name': 'NacelleSE',
 'package_data': {'NacelleSE': []},
 'package_dir': {'': 'src'},
 'packages': ['NacelleSE'],
 'url': '',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

